apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: harness-ephemeral
  region: us-west-2
  version: "1.22"

# iam:
#   withOIDC: true

# identityProviders:
#   - name:

# iamIdentityMappings:
#   - arn: arn:aws:iam::000000000000:role/myAdminRole
#     groups:
#       - system:masters
#     username: admin
#     noDuplicateARNs: true # prevents shadowing of ARNs

#   - arn: arn:aws:iam::000000000000:user/myUser
#     username: myUser
#     noDuplicateARNs: true # prevents shadowing of ARNs

#   # This will fail if present during cluster creation as the namespace needs to exist
#   - serviceName: emr-containers
#     namespace: emr # serviceName requires namespace

#   - account: "000000000000" # account must be configured with no other options

nodeGroups:
  - name: node-group-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      allow: false
  - name: node-group-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      # publicKeyPath: ~/.ssh/ec2_id_rsa.pub
      allow: false

addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest
#
# karpenter:
#   version: "v0.18.0"
